import {
  Product,
  HotWheelsProduct,
  SealedCardProduct,
  SingleCardProduct,
  GradedCardProduct,
  SuppliesProduct,
  Drop,
  Order,
  Address,
  Coupon,
  StoreReview,
} from '@/types/store'

export const MOCK_HOT_WHEELS_PRODUCTS: HotWheelsProduct[] = [
  {
    id: 'hw-1',
    slug: '1971-datsun-240z-super-treasure-hunt',
    title: '1971 Datsun 240Z Super Treasure Hunt ($TH)',
    castingName: '1971 Datsun 240Z',
    productType: 'hot-wheels',
    category: 'hot-wheels',
    series: 'Super Treasure Hunt ($TH)',
    scale: '1:64',
    year: 2022,
    color: 'Spectraflame Aqua Blue',
    wheelType: 'Real Riders Rubber Tires (4-Spoke Gold)',
    packagingCondition: 'Mint on Card (MOC)',
    treasureHuntType: 'Super $TH',
    isChase: true,
    caseCode: 'Case Q',
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2022-HW-8821',
    mrp: 14999,
    price: 11499,
    discountPercent: 23,
    stock: 2,
    rating: 4.9,
    reviewsCount: 84,
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Ultra-rare Mattel factory Super Treasure Hunt grail casting. Features deep Spectraflame aqua paint, Real Riders slotted mag wheels, gold TH flame emblem behind front wheel well, and razor-sharp unpunched short card packaging.',
    features: [
      'Authentic 1:64 scale die-cast metal body & base',
      'Real Riders soft rubber racing compound tires',
      'Spectraflame Aqua Blue metallic lacquer finish',
      'Factory Mint on Card (MOC) with crystal blister bubble',
      '100% BIS Toy Safety Compliant (IS 9873-1:2019)',
    ],
    isFeatured: true,
    isNewArrival: false,
    isBackInStock: true,
    isDropExclusive: false,
    badge: 'Super $TH Grail',
    tags: ['Super Treasure Hunt', 'JDM', 'Datsun', 'Real Riders', 'Spectraflame'],
    createdAt: '2026-09-10T10:00:00Z',
    sku: 'HW-STH-240Z-22',
  },
  {
    id: 'hw-2',
    slug: 'nissan-skyline-gt-r-bnr34-rlc-chrome',
    title: 'Nissan Skyline GT-R (BNR34) Red Line Club Exclusive Chrome',
    castingName: 'Nissan Skyline GT-R (BNR34)',
    productType: 'hot-wheels',
    category: 'hot-wheels',
    series: 'Red Line Club (RLC)',
    scale: '1:64',
    year: 2023,
    color: 'Spectraflame High-Gloss Chrome',
    wheelType: 'Real Riders 6-Spoke Chrome with NISMO Markings',
    packagingCondition: 'Sealed RLC Clamshell',
    treasureHuntType: 'None',
    isChase: true,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2023-HW-9104',
    mrp: 9999,
    price: 7999,
    discountPercent: 20,
    stock: 4,
    rating: 5.0,
    reviewsCount: 142,
    images: [
      'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Official Mattel Creations Red Line Club numbered release. Individually serialized hologram sticker on cardback. Opening die-cast hood reveals fully detailed RB26DETT twin-turbo toy engine bay.',
    features: [
      'Individually numbered hologram security seal',
      'Opening die-cast metal hood with painted engine bay',
      'Spectraflame mirror chrome multi-stage finish',
      'Factory sealed within heavy-duty RLC clamshell case',
      'BIS safety laboratory certified',
    ],
    isFeatured: true,
    isNewArrival: true,
    isBackInStock: false,
    isDropExclusive: true,
    dropId: 'drop-1',
    badge: 'RLC Exclusive',
    tags: ['RLC', 'Skyline', 'GT-R', 'Chrome', 'Opening Hood'],
    createdAt: '2026-10-01T14:00:00Z',
    sku: 'HW-RLC-R34-CHROME',
  },
  {
    id: 'hw-3',
    slug: 'twin-mill-heritage-redline-magenta',
    title: 'Twin Mill Spectraflame Magenta Heritage Redline 1968 Tribute',
    castingName: 'Twin Mill',
    productType: 'hot-wheels',
    category: 'hot-wheels',
    series: 'Red Line Club (RLC)',
    scale: '1:64',
    year: 2021,
    color: 'Spectraflame Magenta',
    wheelType: 'Delrin Bearing Redline Deep Dish Wheels',
    packagingCondition: 'Short Card MOC',
    treasureHuntType: 'None',
    isChase: false,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2021-HW-7731',
    mrp: 3499,
    price: 2799,
    discountPercent: 20,
    stock: 7,
    rating: 4.8,
    reviewsCount: 56,
    images: [
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Ira Gilford’s legendary 1968 Mattel creation recreated in pure Sweet 16 heritage form. Dual exposed supercharged big-block engines cast in polished chrome over Spectraflame magenta.',
    features: [
      'Signature 1968 Sweet Sixteen casting silhouette',
      'Authentic Delrin bearing red-stripe vintage tires',
      'Spectraflame magenta translucent lacquer over zinc die-cast',
      'Short card collector international blister',
      'BIS toy safety tested',
    ],
    isFeatured: false,
    isNewArrival: false,
    isBackInStock: true,
    isDropExclusive: false,
    badge: 'Vintage Redline',
    tags: ['Twin Mill', 'Redline', 'Heritage', 'Sweet 16'],
    createdAt: '2026-08-20T12:00:00Z',
    sku: 'HW-HER-TWINMILL-MAG',
  },
  {
    id: 'hw-4',
    slug: '1967-custom-camaro-antifreeze-green-sth',
    title: '1967 Custom Camaro Antifreeze Green with Opening Hood ($TH)',
    castingName: "'67 Custom Camaro",
    productType: 'hot-wheels',
    category: 'hot-wheels',
    series: 'Super Treasure Hunt ($TH)',
    scale: '1:64',
    year: 2024,
    color: 'Spectraflame Antifreeze Green',
    wheelType: 'Real Riders 5-Spoke Mag Wheels with Rubber Tires',
    packagingCondition: 'Mint on Card (MOC)',
    treasureHuntType: 'Super $TH',
    isChase: true,
    caseCode: 'Case A',
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2024-HW-8899',
    mrp: 4999,
    price: 3899,
    discountPercent: 22,
    stock: 5,
    rating: 4.9,
    reviewsCount: 98,
    images: [
      'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Honoring the very first Hot Wheels casting produced by Mattel in 1968. Features an operable die-cast hood revealing miniature V8 detail, matte black rally stripes, and hidden gold TH logo.',
    features: [
      'Operable die-cast opening hood',
      'Spectraflame Antifreeze finish with twin rally stripes',
      'Real Riders soft compound rubber drag tires',
      'Flawless unpunched card with razor-sharp corners',
      'BIS certified toy safety standards',
    ],
    isFeatured: true,
    isNewArrival: true,
    isBackInStock: false,
    isDropExclusive: false,
    badge: 'Super $TH',
    tags: ['Camaro', 'Super Treasure Hunt', 'Muscle', 'Opening Hood'],
    createdAt: '2026-09-28T09:00:00Z',
    sku: 'HW-STH-CAMARO-AFG',
  },
  {
    id: 'hw-5',
    slug: 'toyota-ae86-sprinter-trueno-car-culture',
    title: 'Toyota AE86 Sprinter Trueno - Car Culture: Mountain Drifters',
    castingName: 'Toyota AE86 Sprinter Trueno',
    productType: 'hot-wheels',
    category: 'hot-wheels',
    series: 'Car Culture Premium',
    scale: '1:64',
    year: 2023,
    color: 'Panda White & Black Two-Tone',
    wheelType: 'Real Riders 8-Spoke White Racing Wheels',
    packagingCondition: 'Mint on Card (MOC)',
    treasureHuntType: 'None',
    isChase: false,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2023-HW-9512',
    mrp: 1299,
    price: 899,
    discountPercent: 31,
    stock: 16,
    rating: 4.8,
    reviewsCount: 210,
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Iconic touge drifter in 1:64 scale. Metal-on-metal die-cast construction with Real Riders white racing wheels, detailed pop-up headlights, and wide premium card art.',
    features: [
      'Full metal/metal body and chassis construction',
      'Real Riders treaded rubber tires',
      'High-resolution multi-pass tampo graphics',
      'Standard Car Culture wide collector blister card',
      'BIS Toy Safety tested formulation',
    ],
    isFeatured: true,
    isNewArrival: false,
    isBackInStock: true,
    isDropExclusive: false,
    badge: 'Best Seller',
    tags: ['AE86', 'Car Culture', 'JDM', 'Mountain Drifters', 'Initial D'],
    createdAt: '2026-08-15T10:00:00Z',
    sku: 'HW-CC-AE86-PANDA',
  },
  {
    id: 'hw-6',
    slug: 'bone-shaker-custom-164-modded-toy-build',
    title: 'Bone Shaker Custom 1:64 Scale Modded Toy Casting with Skull Grill',
    castingName: 'Bone Shaker',
    productType: 'hot-wheels',
    category: 'hot-wheels',
    series: 'Mainline',
    scale: '1:64',
    year: 2024,
    color: 'Hand-Airbrushed Matte Black & Blood Red',
    wheelType: 'Custom Hand-Fitted Staggered Deep Dish Real Riders',
    packagingCondition: 'Loose Mint',
    treasureHuntType: 'None',
    isChase: true,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2024-CUST-104',
    mrp: 1899,
    price: 1499,
    discountPercent: 21,
    stock: 2,
    rating: 4.9,
    reviewsCount: 44,
    images: [
      'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'One-of-a-kind hand-customized 1:64 die-cast toy car. Drill-tapped base, stripped body, coated in multi-stage primer, hand-pinstriped, and mounted with staggered real rider rubber wheels inside a clear acrylic display case.',
    features: [
      'Hand-crafted custom 1:64 miniature die-cast piece',
      'Deep dish real riders staggered wheel swap',
      'Includes 1:64 stackable acrylic display box',
      'Non-toxic collector acrylic enamel finish',
      'BIS compliant toy materials',
    ],
    isFeatured: false,
    isNewArrival: true,
    isBackInStock: false,
    isDropExclusive: false,
    badge: '1:64 Custom Build',
    tags: ['Custom', 'Bone Shaker', 'Wheel Swap', 'Modded', 'Hot Rod'],
    createdAt: '2026-09-20T16:00:00Z',
    sku: 'HW-CUST-BONESHAKER-BLK',
  },
  {
    id: 'hw-7',
    slug: 'porsche-911-gt3-rs-speed-machines',
    title: 'Porsche 911 GT3 RS - Car Culture: Speed Machines',
    castingName: 'Porsche 911 GT3 RS',
    productType: 'hot-wheels',
    category: 'hot-wheels',
    series: 'Car Culture Premium',
    scale: '1:64',
    year: 2024,
    color: 'Shark Blue with Weissach Carbon Details',
    wheelType: 'Speed Machines Co-Molded AeroDisc Wheels',
    packagingCondition: 'Mint on Card (MOC)',
    treasureHuntType: 'None',
    isChase: false,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2024-HW-6632',
    mrp: 1199,
    price: 849,
    discountPercent: 29,
    stock: 11,
    rating: 4.9,
    reviewsCount: 130,
    images: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Hot Wheels Speed Machines edition casting with distinctive high-downforce swan-neck wing and aerodynamic wheel discs. Full metal body and base with sharp tampo headlamp detailing.',
    features: [
      '1:64 scale die-cast zinc metal body and base',
      'High-velocity Speed Machines co-molded wheels',
      'Accurate Weissach pack carbon graphics',
      'Factory fresh carded blister packaging',
      'BIS certified for toy safety',
    ],
    isFeatured: false,
    isNewArrival: true,
    isBackInStock: false,
    isDropExclusive: false,
    badge: 'Speed Machines',
    tags: ['Porsche', 'GT3 RS', 'Speed Machines', 'Car Culture'],
    createdAt: '2026-09-25T11:00:00Z',
    sku: 'HW-CC-911GT3RS-BLU',
  },
  {
    id: 'hw-8',
    slug: 'deora-ii-surf-legends-mainline',
    title: 'Deora II Surf Legends Heritage Mainline with Dual Surfboards',
    castingName: 'Deora II',
    productType: 'hot-wheels',
    category: 'hot-wheels',
    series: 'Mainline',
    scale: '1:64',
    year: 2024,
    color: 'Metallic Cerulean Wave',
    wheelType: 'Chrome 5-Spoke OH5 Wheels',
    packagingCondition: 'Short Card MOC',
    treasureHuntType: 'None',
    isChase: false,
    caseCode: 'Case M',
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2024-HW-1120',
    mrp: 299,
    price: 179,
    discountPercent: 40,
    stock: 42,
    rating: 4.7,
    reviewsCount: 380,
    images: [
      'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Hall of fame futuristic pickup toy car featuring dual detachable clip-in yellow surfboards in the rear bed. Low friction high-speed axles for track racing.',
    features: [
      'Original Nathan Proch Hot Wheels concept design',
      'Dual removable clip-in toy surfboards',
      'Track-optimized low-friction rolling axles',
      'Indian international short blister card',
      'Safe for ages 3+ and adult collectors (BIS certified)',
    ],
    isFeatured: false,
    isNewArrival: false,
    isBackInStock: true,
    isDropExclusive: false,
    badge: 'Mainline Legend',
    tags: ['Deora II', 'Mainline', 'Surf', 'Fantasy', 'Highway 35'],
    createdAt: '2026-07-10T10:00:00Z',
    sku: 'HW-MN-DEORA2-BLU',
  },
  {
    id: 'hw-9',
    slug: 'nissan-silvia-s15-fast-furious-premium',
    title: 'Nissan Silvia S15 - Fast & Furious Premium Die-Cast',
    castingName: 'Nissan Silvia S15 Spec-R',
    productType: 'hot-wheels',
    category: 'hot-wheels',
    series: 'Car Culture Premium',
    scale: '1:64',
    year: 2023,
    color: 'Mona Lisa Blue & Orange Livery',
    wheelType: 'Real Riders 6-Spoke Gunmetal Gray Wheels',
    packagingCondition: 'Mint on Card (MOC)',
    treasureHuntType: 'None',
    isChase: false,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2023-HW-3329',
    mrp: 1399,
    price: 949,
    discountPercent: 32,
    stock: 8,
    rating: 4.9,
    reviewsCount: 175,
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Universal Studios official licensed casting depicting Han’s Mona Lisa S15 from Tokyo Drift. Die-cast metal chassis with authentic Real Riders rubber wheels.',
    features: [
      'Universal Studios Fast & Furious official licensing',
      'Die-cast metal body and base construction',
      'Real Riders soft rubber drift compound tires',
      'Collector card with movie stills backing',
      'BIS toy safety certification (IS 9873)',
    ],
    isFeatured: true,
    isNewArrival: false,
    isBackInStock: true,
    isDropExclusive: false,
    badge: 'Fast & Furious',
    tags: ['Fast & Furious', 'Silvia S15', 'Mona Lisa', 'JDM', 'Car Culture'],
    createdAt: '2026-08-01T14:00:00Z',
    sku: 'HW-FF-S15-MONALISA',
  },
  {
    id: 'hw-10',
    slug: 'volkswagen-drag-bus-rlc-numbered',
    title: 'Volkswagen Drag Bus RLC 20th Anniversary Gold Leaf Edition',
    castingName: 'VW Drag Bus',
    productType: 'hot-wheels',
    category: 'hot-wheels',
    series: 'Red Line Club (RLC)',
    scale: '1:64',
    year: 2022,
    color: 'Spectraflame Gold with Black Panels',
    wheelType: 'Real Riders 5-Spoke Chrome with Cheater Slicks',
    packagingCondition: 'Sealed RLC Clamshell',
    treasureHuntType: 'None',
    isChase: true,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2022-HW-0041',
    mrp: 12999,
    price: 9999,
    discountPercent: 23,
    stock: 2,
    rating: 5.0,
    reviewsCount: 39,
    images: [
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'The heavyweight grail of Hot Wheels collecting. Tipping the scales at over 110 grams of solid die-cast metal. Opening rear body shell reveals chrome fuel cell and massive parachutes.',
    features: [
      'Heavyweight 110g full die-cast alloy construction',
      'Flip-up body reveals chrome chassis and drag engine',
      'Real Riders rear drag slicks with Goodyear lettering',
      'Factory numbered hologram seal',
      'BIS compliant toy formulation',
    ],
    isFeatured: false,
    isNewArrival: false,
    isBackInStock: false,
    isDropExclusive: false,
    badge: 'RLC Heavyweight',
    tags: ['Drag Bus', 'Volkswagen', 'RLC', 'Heavyweight', 'Grail'],
    createdAt: '2026-07-20T10:00:00Z',
    sku: 'HW-RLC-VW-DRAGBUS',
  },
  {
    id: 'hw-11',
    slug: 'ford-gt40-mkii-gulf-livery-team-transport',
    title: '1966 Ford GT40 Mk.II & Retro Rig - Team Transport Premium Set',
    castingName: 'Ford GT40 Mk.II',
    productType: 'hot-wheels',
    category: 'hot-wheels',
    series: 'Team Transport',
    scale: '1:64',
    year: 2024,
    color: 'Gulf Powder Blue & Marigold Orange',
    wheelType: 'Real Riders Pin-Drive Magnesium Racing Wheels',
    packagingCondition: 'Mint on Card (MOC)',
    treasureHuntType: 'None',
    isChase: false,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2024-HW-8819',
    mrp: 2499,
    price: 1899,
    discountPercent: 24,
    stock: 9,
    rating: 4.9,
    reviewsCount: 112,
    images: [
      'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Iconic Le Mans winner paired with an authentic die-cast Retro Rig transport hauler with functional fold-down loading ramp. Officially licensed Gulf Oil livery.',
    features: [
      'Includes 1:64 Ford GT40 and die-cast Retro Rig hauler truck',
      'Working functional loading ramp on hauler',
      'Full metal body and metal chassis on both models',
      'Real Riders racing rubber tires on both vehicles',
      'BIS certified toy safety',
    ],
    isFeatured: true,
    isNewArrival: true,
    isBackInStock: false,
    isDropExclusive: false,
    badge: 'Team Transport',
    tags: ['Gulf', 'Ford GT40', 'Team Transport', 'Le Mans', 'Hauler'],
    createdAt: '2026-09-18T10:00:00Z',
    sku: 'HW-TT-GT40-GULF',
  },
  {
    id: 'hw-12',
    slug: 'mazda-rx-7-fd-boulevard-premium',
    title: '1995 Mazda RX-7 (FD3S) - Boulevard Series Premium',
    castingName: 'Mazda RX-7 FD',
    productType: 'hot-wheels',
    category: 'hot-wheels',
    series: 'Boulevard',
    scale: '1:64',
    year: 2024,
    color: 'Sunburst Yellow with Black Aero Splitter',
    wheelType: 'Real Riders 5-Spoke Bronze Racing Wheels',
    packagingCondition: 'Mint on Card (MOC)',
    treasureHuntType: 'None',
    isChase: false,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2024-HW-3310',
    mrp: 1299,
    price: 899,
    discountPercent: 31,
    stock: 14,
    rating: 4.8,
    reviewsCount: 88,
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'The twin-turbo rotary icon in brilliant competition yellow. Features Mazdaspeed rear wing, bronze Real Riders wheels, and collector-favorite Boulevard card numbering (#82).',
    features: [
      'Metal/metal die-cast casting and chassis',
      'Real Riders bronze competition rubber tires',
      'Authentic FD rotary aero kit detailing',
      'Boulevard numbered collector card',
      'BIS toy safety testing passed',
    ],
    isFeatured: false,
    isNewArrival: true,
    isBackInStock: false,
    isDropExclusive: false,
    badge: 'Boulevard',
    tags: ['RX-7', 'Mazda', 'Boulevard', 'JDM', 'Rotary'],
    createdAt: '2026-09-12T15:00:00Z',
    sku: 'HW-BLVD-RX7-YEL',
  },
]

export const MOCK_TRADING_CARD_PRODUCTS: (SealedCardProduct | SingleCardProduct | GradedCardProduct)[] = [
  // SEALED BOXES & PACKS
  {
    id: 'card-1',
    slug: '2023-24-panini-prizm-premier-league-blaster-box',
    title: '2023-24 Panini Prizm Premier League Soccer Blaster Box (Sealed)',
    productType: 'card-sealed',
    category: 'trading-cards',
    sport: 'Football / Soccer',
    league: 'Premier League',
    brand: 'Panini',
    set: 'Panini Prizm',
    year: 2024,
    packType: 'Blaster Box',
    cardsPerPack: 4,
    packsPerBox: 6,
    guaranteedHits: [
      '1 Blaster-Exclusive Ice Prizm per box on average',
      '3 Silver or Numbered Prizm parallels',
      'Look for Ultra-Rare Color Blast inserts',
    ],
    isSealed: true,
    mrp: 6999,
    price: 5499,
    discountPercent: 21,
    stock: 12,
    rating: 4.9,
    reviewsCount: 164,
    images: [
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Factory-sealed original Panini shrink-wrapped blaster box. The flagship sports card release of the English Premier League season. Chase Erling Haaland, Bukayo Saka, and Kobbie Mainoo rookie cards.',
    features: [
      'Factory shrink-wrapped with Panini hologram tape',
      '6 packs per box, 4 cards per pack (24 cards total)',
      'Blaster exclusive Pink and Red Ice parallels',
      'Guaranteed authentic English Premier League license',
      'Shipped in bubble-armored carton with corner protection',
    ],
    isFeatured: true,
    isNewArrival: true,
    isBackInStock: false,
    isDropExclusive: false,
    badge: 'Sealed Blaster',
    tags: ['Panini Prizm', 'Premier League', 'Sealed Box', 'Blaster', 'Soccer Cards'],
    createdAt: '2026-09-29T10:00:00Z',
    sku: 'CARD-PRIZM-PL-BLASTER-24',
  },
  {
    id: 'card-2',
    slug: '2023-24-topps-chrome-uefa-champions-league-hobby-box',
    title: '2023-24 Topps Chrome UEFA Champions League Hobby Box (Sealed)',
    productType: 'card-sealed',
    category: 'trading-cards',
    sport: 'Football / Soccer',
    league: 'UEFA Champions League',
    brand: 'Topps',
    set: 'Topps Chrome',
    year: 2024,
    packType: 'Hobby Box',
    cardsPerPack: 4,
    packsPerBox: 20,
    guaranteedHits: [
      '1 Guaranteed On-Card Autograph per hobby box',
      '5 Numbered Chrome Refractors',
      'Look for 1/1 SuperFractor & Youthquake inserts',
    ],
    isSealed: true,
    mrp: 24999,
    price: 19999,
    discountPercent: 20,
    stock: 5,
    rating: 5.0,
    reviewsCount: 78,
    images: [
      'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'The crown jewel of European club football collecting. Features full chromium card stock with refractive foil shine. Every hobby box delivers 1 guaranteed certified authentic autograph card from European football superstars.',
    features: [
      'Guaranteed 1 authentic signature card inside every sealed box',
      '20 packs of 4 cards (80 premium chromium cards)',
      'Possibility of 1/1 SuperFractor grails',
      'Original Topps tamper-evident cellophane wrapper',
      'Free insured express courier shipping across India',
    ],
    isFeatured: true,
    isNewArrival: false,
    isBackInStock: true,
    isDropExclusive: true,
    dropId: 'drop-1',
    badge: '1 Guaranteed Auto',
    tags: ['Topps Chrome', 'Champions League', 'Hobby Box', 'Autograph', 'Sealed'],
    createdAt: '2026-09-15T12:00:00Z',
    sku: 'CARD-TOPPS-CHROME-UCL-HB',
  },
  {
    id: 'card-3',
    slug: '2024-topps-match-attax-champions-league-mega-tin',
    title: '2024-25 Topps Match Attax UEFA Champions League Collector Mega Tin',
    productType: 'card-sealed',
    category: 'trading-cards',
    sport: 'Football / Soccer',
    league: 'UEFA Champions League',
    brand: 'Topps',
    set: 'Match Attax',
    year: 2025,
    packType: 'Display Tin',
    cardsPerPack: 66,
    packsPerBox: 1,
    guaranteedHits: [
      '4 Exclusive Classic Celebration Limited Edition Cards',
      '66 Match Attax cards inside embossed collector tin',
      '1 Guaranteed Relic Card (1 in every 4 tins)',
    ],
    isSealed: true,
    mrp: 1499,
    price: 1199,
    discountPercent: 20,
    stock: 35,
    rating: 4.8,
    reviewsCount: 310,
    images: [
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Official UEFA licensed embossed collector storage tin containing 66 game cards including 4 exclusive gold limited editions. Great starter pack for trading meets and Match Attax tournaments.',
    features: [
      'Embossed reusable metal storage tin',
      '66 total cards including 4 limited editions',
      'Includes official gameplay tactical card and code',
      'Factory cellophane sealed',
      'BIS safety certified non-toxic card stock',
    ],
    isFeatured: false,
    isNewArrival: true,
    isBackInStock: true,
    isDropExclusive: false,
    badge: 'Mega Tin',
    tags: ['Match Attax', 'Topps', 'Tin', 'Champions League'],
    createdAt: '2026-09-01T10:00:00Z',
    sku: 'CARD-MATTAX-25-TIN',
  },

  // SINGLES (ROOKIES, PARALLELS, AUTOS)
  {
    id: 'card-4',
    slug: 'jude-bellingham-2020-topps-chrome-rookie-refractor',
    title: 'Jude Bellingham 2020-21 Topps Chrome UEFA Rookie Refractor #83',
    productType: 'card-single',
    category: 'trading-cards',
    sport: 'Football / Soccer',
    league: 'UEFA Champions League',
    brand: 'Topps',
    set: 'Topps Chrome UCL',
    year: 2020,
    player: 'Jude Bellingham',
    team: 'Borussia Dortmund',
    cardNumber: '#83',
    parallel: 'Silver Refractor',
    isRookie: true,
    isAutograph: false,
    isPatchRelic: false,
    cardCondition: 'Raw Gem Mint',
    isUniqueItem: true,
    mrp: 22000,
    price: 18500,
    discountPercent: 16,
    stock: 1,
    rating: 5.0,
    reviewsCount: 24,
    images: [
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'True rookie card of the Real Madrid superstar during his breakout campaign with Borussia Dortmund. High-gloss rainbow silver refractor with pin-sharp corners and 50/50 centering. Stored in Magnetic One-Touch case.',
    features: [
      'Official RC (Rookie Card) shield on front',
      'Authentic rainbow chromium refractor sheen',
      'Ships in brand-new UV-shielded 35pt Magnetic One-Touch case',
      'Physical inspection grade: Raw Gem Mint (PSA 9-10 contender)',
      'Only 1 copy available in store vault',
    ],
    isFeatured: true,
    isNewArrival: false,
    isBackInStock: false,
    isDropExclusive: false,
    badge: 'True Rookie RC',
    tags: ['Bellingham', 'Rookie', 'Topps Chrome', 'Refractor', 'Singles'],
    createdAt: '2026-09-10T14:00:00Z',
    sku: 'SGL-BELLINGHAM-CHROME-20',
  },
  {
    id: 'card-5',
    slug: 'lamine-yamal-2023-topps-chrome-auto-25',
    title: 'Lamine Yamal 2023-24 Topps Chrome Certified Autograph /25 Orange Refractor',
    productType: 'card-single',
    category: 'trading-cards',
    sport: 'Football / Soccer',
    league: 'La Liga / UCL',
    brand: 'Topps',
    set: 'Topps Chrome UEFA',
    year: 2024,
    player: 'Lamine Yamal',
    team: 'FC Barcelona',
    cardNumber: '#AU-LY',
    parallel: 'Orange Refractor /25',
    isRookie: true,
    isAutograph: true,
    isPatchRelic: false,
    printRun: 25,
    serialNumber: '08/25',
    cardCondition: 'Raw Gem Mint',
    isUniqueItem: true,
    mrp: 145000,
    price: 125000,
    discountPercent: 14,
    stock: 1,
    rating: 5.0,
    reviewsCount: 19,
    images: [
      'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'The holy grail of modern football rookies. Certified on-card blue ink autograph from Euro 2024 champion and Barcelona prodigy Lamine Yamal. Hand-serial numbered 08/25 on back.',
    features: [
      'Certified authentic on-card autograph with Topps tamper sticker',
      'Extremely low serial numbered parallel: 08 of 25 only',
      'Euro 2024 Young Player of the Tournament rookie issue',
      'Sealed inside Pro-Mold Magnetic One-Touch holder with penny sleeve',
      'High-value armored insured logistics courier delivery',
    ],
    isFeatured: true,
    isNewArrival: true,
    isBackInStock: false,
    isDropExclusive: true,
    dropId: 'drop-1',
    badge: 'Numbered 08/25 Auto',
    tags: ['Lamine Yamal', 'Autograph', 'Numbered /25', 'Barcelona', 'Grail'],
    createdAt: '2026-10-02T10:00:00Z',
    sku: 'SGL-YAMAL-AUTO-25',
  },
  {
    id: 'card-6',
    slug: 'erling-haaland-2020-panini-prizm-premier-league-silver',
    title: 'Erling Haaland 2022 Panini Prizm Premier League Silver Prizm #1',
    productType: 'card-single',
    category: 'trading-cards',
    sport: 'Football / Soccer',
    league: 'Premier League',
    brand: 'Panini',
    set: 'Panini Prizm',
    year: 2022,
    player: 'Erling Haaland',
    team: 'Manchester City',
    cardNumber: '#1',
    parallel: 'Silver Prizm',
    isRookie: false,
    isAutograph: false,
    isPatchRelic: false,
    cardCondition: 'Raw Gem Mint',
    isUniqueItem: true,
    mrp: 12500,
    price: 9999,
    discountPercent: 20,
    stock: 1,
    rating: 4.9,
    reviewsCount: 32,
    images: [
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'First Manchester City Premier League Prizm card of the Norwegian goal machine. Card #1 in the checklist featuring brilliant reflective silver prizm finish.',
    features: [
      'Card #1 of the historic 2022-23 treble season checklist',
      'Reflective Silver Prizm holographic shine',
      'Encased in 35pt magnetic case',
      'Flawless 50/50 centering and sharp foil stamps',
      'Unique single card listing (1 available)',
    ],
    isFeatured: false,
    isNewArrival: false,
    isBackInStock: true,
    isDropExclusive: false,
    badge: 'Silver Prizm',
    tags: ['Haaland', 'Manchester City', 'Prizm', 'Silver', 'Premier League'],
    createdAt: '2026-09-05T11:00:00Z',
    sku: 'SGL-HAALAND-PRIZM-SILVER',
  },

  // GRADED SLABS (PSA / BGS)
  {
    id: 'card-7',
    slug: 'kylian-mbappe-2018-panini-prizm-world-cup-psa-10',
    title: 'Kylian Mbappé 2018 Panini Prizm World Cup Rookie #80 - PSA 10 Gem Mint',
    productType: 'card-graded',
    category: 'trading-cards',
    sport: 'Football / Soccer',
    league: 'FIFA World Cup',
    brand: 'Panini',
    set: 'Panini Prizm World Cup Russia 2018',
    year: 2018,
    player: 'Kylian Mbappé',
    team: 'France National Team',
    cardNumber: '#80',
    parallel: 'Base Prizm',
    isRookie: true,
    isAutograph: false,
    isPatchRelic: false,
    gradingCompany: 'PSA',
    grade: '10 Gem Mint',
    certNumber: '64829104',
    popReport: { popHigher: 0, popTotal: 980 },
    slabCondition: 'Clean Scratch-Free',
    isUniqueItem: true,
    mrp: 95000,
    price: 82000,
    discountPercent: 14,
    stock: 1,
    rating: 5.0,
    reviewsCount: 42,
    images: [
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'The defining soccer modern grail card. Certified PSA 10 Gem Mint debut card of Kylian Mbappé from the 2018 World Cup where he won the trophy with France. Encapsulated in sonic-welded PSA tamper-evident slab with lighthouse security logo.',
    features: [
      'Highest possible grade: PSA 10 Gem Mint',
      'Official PSA Certification #64829104 verified on PSA database',
      'Zero population higher (highest grade possible)',
      'France 2018 World Cup Championship rookie issue',
      'Fitted with protective graded card sleeve & shipped in armored vault box',
    ],
    isFeatured: true,
    isNewArrival: false,
    isBackInStock: true,
    isDropExclusive: false,
    badge: 'PSA 10 Gem Mint',
    tags: ['Mbappe', 'PSA 10', 'World Cup', 'Rookie', 'Graded Slab'],
    createdAt: '2026-09-01T12:00:00Z',
    sku: 'SLAB-MBAPPE-PSA10-2018',
  },
  {
    id: 'card-8',
    slug: 'cristiano-ronaldo-2003-mega-craques-psa-9',
    title: 'Cristiano Ronaldo 2003 Mega Craques Sporting CP Rookie #28 - PSA 9 Mint',
    productType: 'card-graded',
    category: 'trading-cards',
    sport: 'Football / Soccer',
    league: 'Primeira Liga',
    brand: 'Panini',
    set: 'Mega Craques',
    year: 2003,
    player: 'Cristiano Ronaldo',
    team: 'Sporting CP',
    cardNumber: '#28',
    parallel: 'Base Vintage',
    isRookie: true,
    isAutograph: false,
    isPatchRelic: false,
    gradingCompany: 'PSA',
    grade: '9 Mint',
    certNumber: '48201991',
    popReport: { popHigher: 88, popTotal: 340 },
    slabCondition: 'Clean Scratch-Free',
    isUniqueItem: true,
    mrp: 350000,
    price: 310000,
    discountPercent: 11,
    stock: 1,
    rating: 5.0,
    reviewsCount: 15,
    images: [
      'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'One of the most valuable soccer trading cards in history. The official rookie card of Cristiano Ronaldo in his green & white Sporting CP shirt before signing for Manchester United. Certified PSA 9 Mint.',
    features: [
      'Certified PSA 9 Mint condition for 2003 vintage stock',
      'Official Sporting CP debut rookie card',
      'Verified PSA cert barcode and watermark tag',
      'Extremely low survival rate in high grade',
      'Shipped via fully insured armored logistics with verification certificate',
    ],
    isFeatured: true,
    isNewArrival: false,
    isBackInStock: false,
    isDropExclusive: false,
    badge: 'Historic Grail',
    tags: ['Cristiano Ronaldo', 'CR7', 'Sporting CP', 'PSA 9', 'Historic Rookie'],
    createdAt: '2026-08-10T11:00:00Z',
    sku: 'SLAB-CR7-PSA9-2003',
  },
  {
    id: 'card-9',
    slug: 'pedri-2020-topps-chrome-rookie-bgs-95-true-gem',
    title: 'Pedri 2020-21 Topps Chrome Rookie Refractor #49 - BGS 9.5 True Gem',
    productType: 'card-graded',
    category: 'trading-cards',
    sport: 'Football / Soccer',
    league: 'UEFA Champions League',
    brand: 'Topps',
    set: 'Topps Chrome UCL',
    year: 2020,
    player: 'Pedri',
    team: 'FC Barcelona',
    cardNumber: '#49',
    parallel: 'Refractor',
    isRookie: true,
    isAutograph: false,
    isPatchRelic: false,
    gradingCompany: 'BGS',
    grade: '9.5 True Gem',
    subgrades: { centering: 9.5, corners: 9.5, edges: 9.5, surface: 9.5 },
    certNumber: '001488921',
    slabCondition: 'Clean Scratch-Free',
    isUniqueItem: true,
    mrp: 38000,
    price: 32000,
    discountPercent: 16,
    stock: 1,
    rating: 5.0,
    reviewsCount: 18,
    images: [
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'True Gem Beckett grading slab featuring all four 9.5 subgrades. Golden Boy winner Pedri in Barcelona colors on vibrant chromium refractor stock.',
    features: [
      'Beckett BGS 9.5 True Gem (all 4 subgrades 9.5+)',
      'Subgrades: Centering 9.5, Corners 9.5, Edges 9.5, Surface 9.5',
      'Thick crystal-clear BGS slab with inner archival sleeve',
      'Barcelona Golden Boy award-winning season rookie',
      'Vault certified single copy',
    ],
    isFeatured: false,
    isNewArrival: true,
    isBackInStock: false,
    isDropExclusive: false,
    badge: 'BGS 9.5 Quad Gem',
    tags: ['Pedri', 'BGS 9.5', 'True Gem', 'Barcelona', 'Topps Chrome'],
    createdAt: '2026-09-22T14:00:00Z',
    sku: 'SLAB-PEDRI-BGS95-2020',
  },
]

export const MOCK_SUPPLIES_PRODUCTS: SuppliesProduct[] = [
  {
    id: 'sup-1',
    slug: 'hot-wheels-blister-protectors-10-pack',
    title: 'CrateMeet Armored Hot Wheels Blister Protectors (10-Pack Clamshell Cases)',
    productType: 'supplies',
    category: 'supplies',
    supplyType: 'Blister Clamshell Protector',
    packSize: 10,
    compatibility: 'Fits Hot Wheels Standard & Short Blister Cards, Matchbox, Kaido House',
    mrp: 899,
    price: 599,
    discountPercent: 33,
    stock: 80,
    rating: 4.9,
    reviewsCount: 240,
    images: [
      'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Heavy duty 0.50mm acid-free crystal-clear PET clamshell cases specifically molded for Hot Wheels blisters. Prevents corner bending, bubble damage, and shelf wear.',
    features: [
      '99% UV-Shield filter prevents blister card color fade',
      'Dual snap-locking tabs keep cases firmly closed',
      'Reinforced rigid hanging hole allows wall display',
      'Pack of 10 crystal-clear cases',
      'Archival safe PET polymer (100% recyclable)',
    ],
    isFeatured: true,
    isNewArrival: false,
    isBackInStock: true,
    isDropExclusive: false,
    badge: 'Top Supply',
    tags: ['Protector', 'Blister Case', 'Hot Wheels Supplies', 'Clamshell'],
    createdAt: '2026-08-01T10:00:00Z',
    sku: 'SUP-HW-PROT-10PK',
  },
  {
    id: 'sup-2',
    slug: 'one-touch-magnetic-card-holders-35pt-5-pack',
    title: 'UltraVault 35pt Magnetic One-Touch Card Holders (Pack of 5)',
    productType: 'supplies',
    category: 'supplies',
    supplyType: 'One-Touch Magnetic Cases',
    packSize: 5,
    compatibility: 'Fits all standard 35pt trading cards (Prizm, Chrome, Match Attax)',
    mrp: 1499,
    price: 1099,
    discountPercent: 27,
    stock: 65,
    rating: 4.9,
    reviewsCount: 180,
    images: [
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Premium gold magnet snap closure cases with recessed arrowhead corners so card corners never make contact. Laboratory tested UV blocking technology.',
    features: [
      'Recessed diamond corners to protect delicate card corners',
      'Strong gold neodymium magnet closure',
      'UV-blocking additives to prevent sun bleaching',
      'Ultra clear acid-free laboratory tested resin',
      'Pack of 5 individual magnetic cases',
    ],
    isFeatured: false,
    isNewArrival: false,
    isBackInStock: true,
    isDropExclusive: false,
    badge: 'Best Seller',
    tags: ['Magnetic Case', 'One Touch', '35pt', 'Card Supplies'],
    createdAt: '2026-08-10T12:00:00Z',
    sku: 'SUP-MAG-35PT-5PK',
  },
]

export const ALL_PRODUCTS: Product[] = [
  ...MOCK_HOT_WHEELS_PRODUCTS,
  ...MOCK_TRADING_CARD_PRODUCTS,
  ...MOCK_SUPPLIES_PRODUCTS,
]

export const MOCK_DROPS: Drop[] = [
  {
    id: 'drop-1',
    slug: 'october-grail-fever-rlc-prizm',
    title: 'Midnight Grail Fever: RLC Chrome R34 & Topps Chrome Hobby Box',
    tagline: 'Exclusive drop limited to verified collectors. Strict limit of 2 items per customer.',
    description: 'Western India’s premiere collector drop featuring the numbered RLC Skyline GT-R (BNR34) in high-gloss Spectraflame Chrome alongside sealed 2023-24 Topps Chrome UCL Hobby Boxes with 1 guaranteed autograph per box.',
    category: 'mixed',
    bannerImage: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=1200&q=80',
    status: 'live',
    startsAt: '2026-10-06T18:00:00Z',
    endsAt: '2026-10-08T06:00:00Z',
    itemIds: ['hw-2', 'card-2', 'card-5'],
    maxPerCustomer: 2,
    totalStock: 35,
    remainingStock: 9,
    waitlistCount: 284,
  },
  {
    id: 'drop-2',
    slug: 'diwali-super-treasure-hunt-vault-drop',
    title: 'Diwali Super Treasure Hunt & Prizm Gold Vault Drop',
    tagline: 'Festive allocation of 15 factory unpunched Super $TH castings and 1/1 cards.',
    description: 'Curated by senior collectors for the festival of lights. Featuring Datsun 240Z $TH, 67 Camaro Redline, and serial numbered European soccer rookies.',
    category: 'hot-wheels',
    bannerImage: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80',
    status: 'upcoming',
    startsAt: '2026-10-12T14:30:00Z',
    endsAt: '2026-10-14T23:59:00Z',
    itemIds: ['hw-1', 'hw-4', 'card-4'],
    maxPerCustomer: 1,
    totalStock: 25,
    remainingStock: 25,
    waitlistCount: 640,
  },
  {
    id: 'drop-3',
    slug: 'vintage-sweet-16-heritage-drop',
    title: 'Vintage 1968 Sweet 16 & Premier League Inaugural Drop',
    tagline: 'Closed archive drop. All allocated units fulfilled and delivered.',
    description: 'Historical heritage castings from 1968 and vintage early Premier League card wax boxes.',
    category: 'mixed',
    bannerImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80',
    status: 'ended',
    startsAt: '2026-09-01T12:00:00Z',
    endsAt: '2026-09-03T12:00:00Z',
    itemIds: ['hw-3', 'card-8'],
    maxPerCustomer: 1,
    totalStock: 20,
    remainingStock: 0,
    waitlistCount: 520,
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-9921',
    invoiceNumber: 'INV-CRATE-2026-0941',
    createdAt: '2026-10-06T14:30:00Z',
    status: 'IN_TRANSIT',
    items: [
      { product: MOCK_HOT_WHEELS_PRODUCTS[0], quantity: 1, priceAtPurchase: 11499 },
      { product: MOCK_SUPPLIES_PRODUCTS[0], quantity: 1, priceAtPurchase: 599 },
    ],
    subtotal: 12098,
    gst: 2177,
    shippingFee: 0,
    discount: 500,
    total: 11598,
    shippingAddress: {
      id: 'addr-1',
      fullName: 'Shreyash Srivastava',
      phone: '+91 98201 55902',
      addressLine: 'Flat 402, Sea Green Apartments, Carter Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400050',
      isDefault: true,
    },
    paymentMethod: 'UPI',
    paymentStatus: 'PAID',
    courier: 'BlueDart Air Express',
    trackingAwb: 'BD-884920192',
    timeline: [
      { status: 'PACKED', title: 'Box Packed & Corner Edge Guards Fitted', description: 'Item verified in mint blister condition. Bubble wrapped in double-wall carton.', timestamp: '2026-10-06 15:45', location: 'CrateMeet WMS Hub (Mumbai)', completed: true },
      { status: 'LABEL_GENERATED', title: 'BlueDart Air AWB Generated', description: 'Manifest barcode BD-884920192 printed.', timestamp: '2026-10-06 16:10', location: 'Bandra Sorting Center', completed: true },
      { status: 'PICKED_UP', title: 'Carrier Scanned Package', description: 'Package picked up by BlueDart Express logistics team.', timestamp: '2026-10-06 17:30', location: 'BKC Air Gateway', completed: true },
      { status: 'IN_TRANSIT', title: 'Departed Mumbai Central Air Hub', description: 'Package in transit for local delivery station dispatch.', timestamp: '2026-10-06 21:15', location: 'Santacruz Hub', completed: true },
      { status: 'OUT_FOR_DELIVERY', title: 'Out for Delivery', description: 'Rider assigned with express delivery vehicle.', timestamp: 'Expected Tomorrow 11:00 AM', completed: false },
      { status: 'DELIVERED', title: 'Delivered', description: 'Delivered with recipient signature verification.', timestamp: 'Expected Tomorrow 02:00 PM', completed: false },
    ],
  },
  {
    id: 'ORD-9840',
    invoiceNumber: 'INV-CRATE-2026-0812',
    createdAt: '2026-09-28T11:20:00Z',
    deliveredAt: '2026-09-30T14:15:00Z',
    status: 'DELIVERED',
    items: [
      { product: MOCK_TRADING_CARD_PRODUCTS[0], quantity: 2, priceAtPurchase: 5499 },
    ],
    subtotal: 10998,
    gst: 1979,
    shippingFee: 0,
    discount: 1000,
    total: 9998,
    shippingAddress: {
      id: 'addr-1',
      fullName: 'Shreyash Srivastava',
      phone: '+91 98201 55902',
      addressLine: 'Flat 402, Sea Green Apartments, Carter Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400050',
      isDefault: true,
    },
    paymentMethod: 'Card',
    paymentStatus: 'PAID',
    courier: 'Delhivery Surface',
    trackingAwb: 'DL-991204812',
    timeline: [
      { status: 'PACKED', title: 'Armored Packing Sealed', description: 'Card boxes sealed in bubble envelope.', timestamp: '2026-09-28 12:00', location: 'WMS Central', completed: true },
      { status: 'PICKED_UP', title: 'Handed to Delhivery Courier', description: 'Scanned at facility.', timestamp: '2026-09-28 15:30', location: 'Bandra Station', completed: true },
      { status: 'IN_TRANSIT', title: 'In Transit', description: 'Transferred via regional hub.', timestamp: '2026-09-29 09:00', location: 'Mumbai Gateway', completed: true },
      { status: 'OUT_FOR_DELIVERY', title: 'Out for Delivery', description: 'Assigned to courier partner.', timestamp: '2026-09-30 09:30', location: 'Bandra Delivery Center', completed: true },
      { status: 'DELIVERED', title: 'Delivered to Customer', description: 'Received by customer. Packaging intact.', timestamp: '2026-09-30 14:15', location: 'Mumbai 400050', completed: true },
    ],
  },
]

export const MOCK_COUPONS: Coupon[] = [
  { code: 'CRATE10', type: 'percent', value: 10, minOrderValue: 999, description: '10% off on all orders above ₹999', expiresAt: '2026-12-31' },
  { code: 'MINT200', type: 'flat', value: 200, minOrderValue: 1499, description: '₹200 instant savings on orders above ₹1,499', expiresAt: '2026-11-30' },
  { code: 'FIRSTDROP', type: 'percent', value: 15, minOrderValue: 2499, description: '15% off for new collector orders', expiresAt: '2026-12-31' },
]

export const MOCK_REVIEWS: StoreReview[] = [
  {
    id: 'rev-1',
    productId: 'hw-1',
    authorName: 'Kabir Mehta',
    authorLocation: 'Mumbai',
    rating: 5,
    title: 'Pristine international short card condition!',
    comment: 'Was nervous ordering a Super $TH online in India, but CrateMeet packed it in a heavy clamshell with corner edge guards and zero card crease. Verified real rider rubber tires. Truly collector-grade packaging.',
    verifiedPurchase: true,
    createdAt: '2026-09-28T16:20:00Z',
  },
  {
    id: 'rev-2',
    productId: 'card-1',
    authorName: 'Ananya Deshmukh',
    authorLocation: 'Bengaluru',
    rating: 5,
    title: 'Pulled a Bukayo Saka Red Ice Prizm!',
    comment: 'Original Panini shrink wrap with hologram seal intact. Received the box in 24 hours via BlueDart air. Hits were clean with sharp edges.',
    verifiedPurchase: true,
    createdAt: '2026-10-02T11:40:00Z',
  },
  {
    id: 'rev-3',
    productId: 'hw-2',
    authorName: 'Rohit Shenoy',
    authorLocation: 'Pune',
    rating: 5,
    title: 'Spectraflame chrome R34 is breathtaking in hand',
    comment: 'The opening hood engine detail is on another level compared to mainlines. Serial number matched the Mattel invoice card.',
    verifiedPurchase: true,
    createdAt: '2026-10-04T18:10:00Z',
  },
]
