import { ShopProduct, ShopOrder } from '@/types'

export const MOCK_SHOP_PRODUCTS: ShopProduct[] = [
  {
    id: 'hw-prod-1',
    title: '1971 Datsun 240Z Super Treasure Hunt ($TH)',
    castingName: '1971 Datsun 240Z',
    series: 'Super Treasure Hunt ($TH)',
    scale: '1:64',
    brand: 'Hot Wheels (Mattel)',
    releaseYear: 2022,
    wheelType: 'Real Riders Rubber Tires with 4-Spoke Gold Rims',
    colorDeco: 'Spectraflame Aqua Blue with $TH Gold Flame Logo & Side Stripes',
    packagingCondition: 'Mint on Card (MOC)',
    bisCertified: true,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2022-HW-8821',
    mrp: 14999,
    price: 11499,
    discountPercent: 23,
    rating: 4.9,
    reviewsCount: 84,
    primeDelivery: true,
    stockCount: 3,
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Authentic 1:64 scale die-cast toy casting manufactured by Mattel. Features ultra-rare Spectraflame paint, Real Riders rubber wheels, and pristine unpunched international short card packaging. Collector-verified $TH grail piece.',
    features: [
      '1:64 Die-Cast Metal Body & Metal Chassis',
      'Real Riders Deep-Dish Rubber Racing Tires',
      'Spectraflame Aqua Lacquer with Hidden TH Stamp',
      'Factory Mint on Card (MOC) with razor sharp corners',
      '100% BIS Toy Safety Compliant (IS 9873-1:2019)',
    ],
    sku: 'HW-STH-240Z-22',
    warehouseLocation: 'A-01-B-04',
    weightGrams: 48,
    dimensionsCm: { length: 16.5, width: 10.8, height: 3.5 },
    badge: 'Super TH Grail',
  },
  {
    id: 'hw-prod-2',
    title: 'Nissan Skyline GT-R (BNR34) Red Line Club (RLC) Chrome',
    castingName: 'Nissan Skyline GT-R (BNR34)',
    series: 'Red Line Club (RLC)',
    scale: '1:64',
    brand: 'Hot Wheels (Mattel)',
    releaseYear: 2023,
    wheelType: 'Real Riders 6-Spoke Chrome with Rubber Tires',
    colorDeco: 'Spectraflame High-Gloss Chrome with NISMO Z-Tune Carbon Details',
    packagingCondition: 'Sealed RLC Clamshell',
    bisCertified: true,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2023-HW-9104',
    mrp: 9999,
    price: 7999,
    discountPercent: 20,
    rating: 5.0,
    reviewsCount: 142,
    primeDelivery: true,
    stockCount: 5,
    images: [
      'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Official Mattel Creations RLC Exclusive die-cast casting. Individually numbered collector badge on rear backing. Features opening hood showcasing twin-turbo RB26DETT engine detail.',
    features: [
      'Individually Numbered Collector Hologram Seal',
      'Full Die-Cast Z-Tune Body with Opening Hood Engine Bay',
      'Heavyweight Metal Base with Real Riders Staggered Wheels',
      'Enclosed in Mattel Factory Acrylic Clamshell Protector',
      'BIS Tested for Collector Toy Safety',
    ],
    sku: 'HW-RLC-R34-CHROME',
    warehouseLocation: 'A-01-B-08',
    weightGrams: 55,
    dimensionsCm: { length: 17.0, width: 11.5, height: 4.0 },
    badge: 'RLC Exclusive',
  },
  {
    id: 'hw-prod-3',
    title: 'Twin Mill Spectraflame Magenta Heritage Redline Tribute',
    castingName: 'Twin Mill',
    series: 'Red Line Club (RLC)',
    scale: '1:64',
    brand: 'Hot Wheels (Mattel)',
    releaseYear: 2021,
    wheelType: 'Delrin Bearing Redline Deep Dish Wheels',
    colorDeco: 'Spectraflame Magenta with Dual Polished Superchargers',
    packagingCondition: 'Short Card MOC',
    bisCertified: true,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2021-HW-7731',
    mrp: 3499,
    price: 2799,
    discountPercent: 20,
    rating: 4.8,
    reviewsCount: 56,
    primeDelivery: true,
    stockCount: 8,
    images: [
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Tribute to Ira Gilford’s legendary 1968 Mattel creation. Hand-polished die-cast casting with dual massive big-block engine blowers and original style red-striped tires.',
    features: [
      'Historic 1968 Sweet Sixteen Signature Casting',
      'Delrin Low-Friction Bearing Redline Wheels',
      'Spectraflame Magenta Metallic Paint Scheme',
      'Mint on Card Short International Blister',
      'BIS Certified 1:64 Scale Collectible Toy',
    ],
    sku: 'HW-HER-TWINMILL-MAG',
    warehouseLocation: 'A-02-A-01',
    weightGrams: 50,
    dimensionsCm: { length: 16.5, width: 10.8, height: 3.5 },
    badge: 'Best Seller',
  },
  {
    id: 'hw-prod-4',
    title: '1967 Custom Camaro Antifreeze Green with Opening Hood',
    castingName: "'67 Custom Camaro",
    series: 'Super Treasure Hunt ($TH)',
    scale: '1:64',
    brand: 'Hot Wheels (Mattel)',
    releaseYear: 2024,
    wheelType: 'Real Riders 5-Spoke Mag Wheels with Rubber Tires',
    colorDeco: 'Spectraflame Antifreeze Green with Matte Black Rally Stripes',
    packagingCondition: 'Mint on Card (MOC)',
    bisCertified: true,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2024-HW-8899',
    mrp: 4999,
    price: 3899,
    discountPercent: 22,
    rating: 4.9,
    reviewsCount: 98,
    primeDelivery: true,
    stockCount: 6,
    images: [
      'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Super Treasure Hunt variant celebrating the very first Hot Wheels casting produced by Mattel in 1968. Features working opening die-cast hood and Real Riders rubber wheels.',
    features: [
      'Working Articulated Opening Die-Cast Hood',
      'Spectraflame Antifreeze Lustre Finish',
      'Real Riders Soft Compound Rubber Tires',
      'Unbent Card Backing with Pristine Bubble Seal',
      'Toy Safety BIS IS 9873 Certified',
    ],
    sku: 'HW-STH-CAMARO-AFG',
    warehouseLocation: 'A-02-A-05',
    weightGrams: 52,
    dimensionsCm: { length: 16.5, width: 10.8, height: 3.5 },
    badge: "Amazon's Choice",
  },
  {
    id: 'hw-prod-5',
    title: 'Toyota AE86 Sprinter Trueno - Car Culture: Mountain Drifters',
    castingName: 'Toyota AE86 Sprinter Trueno',
    series: 'Car Culture Premium',
    scale: '1:64',
    brand: 'Hot Wheels (Mattel)',
    releaseYear: 2023,
    wheelType: 'Real Riders 8-Spoke White Racing Wheels',
    colorDeco: 'Panda White & Black Two-Tone Livery with Pop-Up Lights',
    packagingCondition: 'Mint on Card (MOC)',
    bisCertified: true,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2023-HW-9512',
    mrp: 1299,
    price: 899,
    discountPercent: 31,
    rating: 4.8,
    reviewsCount: 210,
    primeDelivery: true,
    stockCount: 14,
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Highly sought-after Mattel Car Culture Premium release. Full metal/metal construction with real rubber tires. Perfect representation of touge drifting heritage in 1:64 miniature.',
    features: [
      'Premium Metal Body & Metal Chassis Base',
      'Real Riders Rubber Treaded Tires',
      'Detailed Tampo Headlights, Tail Lights & Fujiwara Livery',
      'Standard Premium Car Culture Wide Blister Card',
      'BIS Tested Safe Toy Formulation',
    ],
    sku: 'HW-CC-AE86-PANDA',
    warehouseLocation: 'B-01-A-02',
    weightGrams: 46,
    dimensionsCm: { length: 16.5, width: 13.5, height: 3.5 },
    badge: 'Best Seller',
  },
  {
    id: 'hw-prod-6',
    title: 'Bone Shaker Custom 1:64 Scale Modded Toy Casting with Skull Grill',
    castingName: 'Bone Shaker',
    series: 'Mainline',
    scale: '1:64',
    brand: 'Hot Wheels (Mattel)',
    releaseYear: 2024,
    wheelType: 'Custom Hand-Fitted Staggered Deep Dish Real Riders',
    colorDeco: 'Hand-Airbrushed Matte Black with Blood Red Pinstripes',
    packagingCondition: 'Custom Acrylic Case',
    bisCertified: true,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2024-CUST-104',
    mrp: 1899,
    price: 1499,
    discountPercent: 21,
    rating: 4.9,
    reviewsCount: 44,
    primeDelivery: true,
    stockCount: 2,
    images: [
      'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Masterfully customized 1:64 die-cast toy car. Drilled base, stripped casting, painted in multi-stage primer with custom real-rider wheel swap and acrylic display case.',
    features: [
      'Hand-Customized 1:64 Scale Die-Cast Toy',
      'Custom Real Riders Staggered Wheels Swapped',
      'Chrome Skull Grille & Exposed Quad-Pipes',
      'Comes Mounted Inside 1:64 Magnetic Acrylic Case',
      'Non-Toxic Acrylic Enamels (BIS Compliant)',
    ],
    sku: 'HW-CUST-BONESHAKER-BLK',
    warehouseLocation: 'B-01-A-07',
    weightGrams: 75,
    dimensionsCm: { length: 12.0, width: 6.0, height: 5.5 },
    badge: 'Limited Stock',
  },
  {
    id: 'hw-prod-7',
    title: 'Porsche 911 GT3 RS - Car Culture: Speed Machines',
    castingName: 'Porsche 911 GT3 RS',
    series: 'Car Culture Premium',
    scale: '1:64',
    brand: 'Hot Wheels (Mattel)',
    releaseYear: 2024,
    wheelType: 'Real Riders AeroDisc Racing Wheels',
    colorDeco: 'Shark Blue with Weissach Package Carbon Wing',
    packagingCondition: 'Mint on Card (MOC)',
    bisCertified: true,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2024-HW-6632',
    mrp: 1199,
    price: 849,
    discountPercent: 29,
    rating: 4.9,
    reviewsCount: 130,
    primeDelivery: true,
    stockCount: 11,
    images: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Hot Wheels Speed Machines line release with co-molded aerodynamic wheels and full die-cast chassis. Distinctive high-downforce rear wing and vented front fenders.',
    features: [
      '1:64 Scale Die-Cast Metal Construction',
      'Speed Machines High-Velocity Co-Molded Wheels',
      'Detailed GT3 RS Graphics and Headlamp Tampo',
      'Factory Fresh Carded Condition',
      'BIS Certification Certified for Toy Safety',
    ],
    sku: 'HW-CC-911GT3RS-BLU',
    warehouseLocation: 'B-02-C-01',
    weightGrams: 47,
    dimensionsCm: { length: 16.5, width: 13.5, height: 3.5 },
    badge: "Amazon's Choice",
  },
  {
    id: 'hw-prod-8',
    title: 'Deora II Surf Legends Heritage Mainline with Dual Surfboards',
    castingName: 'Deora II',
    series: 'Mainline',
    scale: '1:64',
    brand: 'Hot Wheels (Mattel)',
    releaseYear: 2024,
    wheelType: 'Chrome 5-Spoke OH5 Wheels',
    colorDeco: 'Metallic Cerulean Wave with Yellow Snap-on Surfboards',
    packagingCondition: 'Short Card MOC',
    bisCertified: true,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2024-HW-1120',
    mrp: 299,
    price: 179,
    discountPercent: 40,
    rating: 4.7,
    reviewsCount: 380,
    primeDelivery: true,
    stockCount: 42,
    images: [
      'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'The world-famous Hot Wheels Hall of Fame concept toy car! Features dual detachable molded plastic surfboards mounted in the rear truck bed. Fast-rolling mainline axles.',
    features: [
      'Hot Wheels Original Fantasy Legend Casting',
      'Dual Detachable Clip-In Miniature Surfboards',
      'Track-Optimized Low Friction High-Speed Axles',
      'Indian International Short Blister Card',
      'BIS Tested - Safe for Ages 3 & Collectors',
    ],
    sku: 'HW-MN-DEORA2-BLU',
    warehouseLocation: 'C-01-D-03',
    weightGrams: 42,
    dimensionsCm: { length: 16.5, width: 10.8, height: 3.5 },
    badge: 'Best Seller',
  },
  {
    id: 'hw-prod-9',
    title: 'Nissan Silvia S15 - Fast & Furious Premium Die-Cast',
    castingName: 'Nissan Silvia S15 Spec-R',
    series: 'Car Culture Premium',
    scale: '1:64',
    brand: 'Hot Wheels (Mattel)',
    releaseYear: 2023,
    wheelType: 'Real Riders 6-Spoke Gray Racing Wheels',
    colorDeco: 'Mona Lisa Blue & Orange Livery (Tokyo Drift)',
    packagingCondition: 'Mint on Card (MOC)',
    bisCertified: true,
    bisRegistrationNo: 'IS 9873 / BIS-TOY-2023-HW-3329',
    mrp: 1399,
    price: 949,
    discountPercent: 32,
    rating: 4.9,
    reviewsCount: 175,
    primeDelivery: true,
    stockCount: 7,
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Officially licensed Fast & Furious Premium Hot Wheels casting. Han’s iconic Mona Lisa S15 with widebody styling, Real Riders rubber wheels, and all-metal construction.',
    features: [
      'Universal Studios Fast & Furious Official Licensing',
      'Die-Cast Metal Body & Base with Real Riders Rubber Wheels',
      'Crisp Screen-Accurate Blue and Orange Tampo Print',
      'Mint on Card Collector Packaging',
      'BIS Toy Safety Certified (IS 9873)',
    ],
    sku: 'HW-FF-S15-MONALISA',
    warehouseLocation: 'B-02-C-05',
    weightGrams: 49,
    dimensionsCm: { length: 16.5, width: 13.5, height: 3.5 },
    badge: "Amazon's Choice",
  },
  {
    id: 'hw-prod-10',
    title: 'Collector Armored Blister Protectors (Pack of 10 Clamshell Cases)',
    castingName: '1:64 Blister Case Protector Pack',
    series: 'Accessories',
    scale: '1:64',
    brand: 'CollectorEvents Vault Supplies',
    releaseYear: 2025,
    wheelType: 'N/A (Protective Equipment)',
    colorDeco: '0.5mm Crystal Clear PET with UV Sun-Fade Inhibitor',
    packagingCondition: 'Sealed Factory Case',
    bisCertified: true,
    bisRegistrationNo: 'IS 9873 / BIS-ACC-2025-01',
    mrp: 899,
    price: 599,
    discountPercent: 33,
    rating: 4.9,
    reviewsCount: 240,
    primeDelivery: true,
    stockCount: 80,
    images: [
      'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Heavy duty 0.50mm acid-free clear clamshell protectors custom molded for Hot Wheels mainline and short card blisters. Prevents corner creasing, edge wear, and UV sunlight fading.',
    features: [
      'Engineered for 1:64 Scale Hot Wheels Standard & Short Cards',
      'Reinforced Rigid Hanging Tab with Dual Snap-Lock Closure',
      '99% UV-Shield Filter Protects Blisters from Discoloration',
      'Pack of 10 High-Clarity Cases',
      'Safe Archival Grade Material',
    ],
    sku: 'ACC-PROT-10PK-PET',
    warehouseLocation: 'D-01-A-01',
    weightGrams: 280,
    dimensionsCm: { length: 20.0, width: 15.0, height: 8.0 },
    badge: 'Best Seller',
  },
]

export const MOCK_INITIAL_ORDERS: ShopOrder[] = [
  {
    id: 'HW-ORD-8821',
    items: [
      {
        productId: 'hw-prod-1',
        title: '1971 Datsun 240Z Super Treasure Hunt ($TH)',
        castingName: '1971 Datsun 240Z',
        series: 'Super Treasure Hunt ($TH)',
        quantity: 1,
        price: 11499,
        image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
        sku: 'HW-STH-240Z-22',
        location: 'A-01-B-04',
        weightGrams: 48,
      },
      {
        productId: 'hw-prod-10',
        title: 'Collector Armored Blister Protectors (Pack of 10)',
        castingName: '1:64 Blister Case Protector Pack',
        series: 'Accessories',
        quantity: 1,
        price: 599,
        image: 'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=800&q=80',
        sku: 'ACC-PROT-10PK-PET',
        location: 'D-01-A-01',
        weightGrams: 280,
      },
    ],
    totalItems: 2,
    subtotal: 12098,
    discount: 500,
    shippingFee: 0,
    totalAmount: 11598,
    customer: {
      name: 'Kabir Mehta',
      phone: '+91 98201 44820',
      email: 'kabir.diecast@example.com',
      address: 'A-402 Silver Sands, Carter Road, Bandra West',
      city: 'Mumbai',
      pincode: '400050',
      state: 'Maharashtra',
    },
    paymentMethod: 'UPI',
    status: 'ALLOCATED',
    createdAt: '2026-10-06T19:40:00Z',
    estimatedDelivery: 'Tomorrow, Oct 8 by 2:00 PM',
    wms: {
      pickWaveId: 'WAVE-2026-10-01',
      recommendedCarton: 'Carton M (24 x 16 x 8 cm)',
      packedWeightKg: 0.35,
    },
  },
  {
    id: 'HW-ORD-8822',
    items: [
      {
        productId: 'hw-prod-5',
        title: 'Toyota AE86 Sprinter Trueno - Car Culture: Mountain Drifters',
        castingName: 'Toyota AE86 Sprinter Trueno',
        series: 'Car Culture Premium',
        quantity: 2,
        price: 899,
        image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
        sku: 'HW-CC-AE86-PANDA',
        location: 'B-01-A-02',
        weightGrams: 92,
      },
    ],
    totalItems: 2,
    subtotal: 1798,
    discount: 0,
    shippingFee: 0,
    totalAmount: 1798,
    customer: {
      name: 'Ananya Deshmukh',
      phone: '+91 99800 23119',
      email: 'ananya.cards@example.com',
      address: 'Flat 12, Sobha Iris, Outer Ring Road, Bellandur',
      city: 'Bengaluru',
      pincode: '560103',
      state: 'Karnataka',
    },
    paymentMethod: 'Card',
    status: 'PACKED',
    createdAt: '2026-10-06T18:15:00Z',
    estimatedDelivery: 'Oct 9 by 6:00 PM',
    wms: {
      pickWaveId: 'WAVE-2026-10-01',
      pickerName: 'Ramesh (Bay 2)',
      pickedAt: '2026-10-06T18:30:00Z',
      recommendedCarton: 'Carton S (18 x 12 x 6 cm)',
      packedWeightKg: 0.22,
      packedAt: '2026-10-06T18:45:00Z',
      courier: 'BlueDart Express',
      trackingAwb: 'BD-882941092',
    },
  },
]
